Studeeric/proj1

src/main/java/com/proj1/Exam.java

Exam aangemaakt.
Potentiele errors ivm missende classes Student & Question

Exam aangemaakt

---

src/main/java/com/proj1/Exam.java

Onderaan nog length naar size gewijzigd.
Ook sysout gemaakt waarbij de askQuestion een tekst kan returnen.

small changes

---

src/main/java/com/proj1/Exam.java

Getter van naam en category gemaakt.

gets in exam

---

src/main/java/com/proj1/Exam.java

voegde toe: getExam() en getQeustion()

---

src/main/java/com/proj1/App.java
src/main/java/com/proj1/Exam.java
src/main/java/com/proj1/Student.java

Wat vragen toegevoegd en wat errors opgepakt zodat dingen werken.

Vragen toegevoegd + paar kleine errors opgepakt

---

src/main/java/com/proj1/App.java
src/main/java/com/proj1/Exam.java

kleine errors opgepakt die ik zag

---

src/main/java/com/proj1/App.java
src/main/java/com/proj1/Exam.java
src/main/java/com/proj1/Question.java

examen kan gemaakt worden maar gelijk error erna

---

src/main/java/com/proj1/App.java

eh kerel Merge DevLucas ja man echt kei veel zin in wouter kijkt heel raar maar dat maakt mij niet uit want ik ben lekker bezig en ik heb een heel lekker broodje gemist maar dat is een goed verhaal waarover ik nu absoluut meer ga vertellen haha sicke toch niet wouter hoopt dat dit snel ophoud maar ik ben lekker op dreef dit gaat zo lekker man eric en wessel zijn nogsteeds niet terug ik ga ervan uit dat wessel een lekker broodje aan het halen oh nee wouter wordt boos help we gaan weer eens lekker door hiermee wessel zit lekker te lezen terwijl ik aan het typen ben maar dat maakt mij niet uit grammatica gaat ook de deur uit samen met de logica daar gaat het niet om wessel jonge ik meen het ik word straks echt kei boos ff zonder hoofdletters maat make me doe it ik ga geen hoofdletters …

studenten toegevoegd

---

src/main/java/com/proj1/App.java

Je kan nu bij menukeuze 7 (in combinatie met mn vorige pull request) opvragen wat alle behaalde examens zijn van de student.

Lijst van behaalde examens werkt

---

src/main/java/com/proj1/App.java

Ook daarbij examen afnemen gestest om te kijken of hij goed "opslaat".
Dit gebeurd. Dus als je examen gehaald hebt dan ziet hij dat ook.

Examstatus werkt.

---

src/main/java/com/proj1/Question.java

added lowwercase support to checkAnswer() in question

---

src/test/java/com/proj1/QuestionTest.java

nu hebben we tests voor Question

tests question

---

src/main/java/com/proj1/App.java

#81 Er wordt nu weergegeven: "De student heeft helaas geen examens gehaald."
#83 Er wordt nu weergegeven: "Student is niet gevonden. U zal nu terugkeren naar het hoofdmenu."
Private Static methode gemaakt in App: pauseMenu(Scanner scanner)
Deze print "Press enter to continue." en wacht daarna op enter.

Invalid Student opgepakt en enter regels netter gemaakt

---

src/main/java/com/proj1/App.java
src/main/java/com/proj1/Student.java
src/test/java/com/proj1/StudentTest.java

eh kerel Merge DevLucas ja man echt kei veel zin in wouter kijkt heel raar maar dat maakt mij niet uit want ik ben lekker bezig en ik heb een heel lekker broodje gemist maar dat is een goed verhaal waarover ik nu absoluut meer ga vertellen haha sicke toch niet wouter hoopt dat dit snel ophoud maar ik ben lekker op dreef dit gaat zo lekker man eric en wessel zijn nogsteeds niet terug ik ga ervan uit dat wessel een lekker broodje aan het halen oh nee wouter wordt boos help we gaan weer eens lekker door hiermee wessel zit lekker te lezen terwijl ik aan het typen ben maar dat maakt mij niet uit grammatica gaat ook de deur uit samen met de logica daar gaat het niet om wessel jonge ik meen het ik word straks echt kei boos ff zonder hoofdletters maat make me doe it ik ga geen hoofdletters …

Test toegevoegd en code opschonen

---

src/main/java/com/proj1/Student.java

zorgt ervoor dat tekst niet op zelfde regel komt als de volgende println

minor aesthetic changes to studentMostPassed

---

UML.drawio
database/[V2]oldDatabase - Copy.Wdf
database/oldDatabase.Wdf
src/main/java/com/proj1/App.java
src/main/java/com/proj1/Init.java
src/main/java/com/proj1/SaveManager.java

Exams can be declared in the savefile using:  
exam:newExam:name:category  
Made SaveManager & Init abstract

Working Exams from savefile, small database changes & abstract classes

---

src/main/java/com/proj1/App.java

mainMenu: scanner.nextInt() wanneer er een string gegeven wordt

mainMenu: scannner.nextInt() maar string

---

src/main/java/com/proj1/App.java

Revert "mainMenu: scannner.nextInt() maar string"

---

src/main/java/com/proj1/Student.java

alles wat aangepast is, is getest

newStudent2 verwijderd en checkstudentnumber uitgebreid

---

src/main/java/com/proj1/App.java
src/main/java/com/proj1/Exam.java

- Nieuwe methode gemaakt die checkt of gevraagde studentnummer:
1. Een nummer is en niet een string
2. Een bestaand nummer is
3. Indien niet bestaat, nieuwe aanmaakt
Clearscreen in printMainMenu() gegooit om lines te besparen.
printAllExams() in Exam gemaakt, eventuele soortgelijke methods in main kunnen er uit.
Voor verdere vragen, vraag Eric

Studentnumber text catch + Exam change

---

src/main/java/com/proj1/App.java

Issue #103 opgelost.
Ook nutteloze method die alle exams print uit App verwijderd.

Menu letter mag & nutteloze method verwijderd

---

src/main/java/com/proj1/App.java

gekke 3 is opgelost, feest

---

database/oldDatabase.Wdf
src/main/java/com/proj1/App.java
src/main/java/com/proj1/Debug.java
src/main/java/com/proj1/ExamManager.java
src/main/java/com/proj1/Question.java
src/main/java/com/proj1/Student.java

Title
Also added a wait method in app to give the impression that our program is doing something.
Checked compatibility w/SaveManager.
Need some monkès to test

DevWouter, Added ExamManager functionality

---

src/main/java/com/proj1/App.java
src/main/java/com/proj1/Exam.java
src/main/java/com/proj1/Question.java

Var werd niet meer gebruikt dus verwijderd.
Public toegevoegd aan twee instance variables .

Useless var verwijderd + public toegevoegd aan vars

---

src/main/java/com/proj1/App.java
src/main/java/com/proj1/Student.java

Issue #150 opgelost.
Pausescreen toegevoegd want dat was de issue. Hij schoot gelijk door naar main menu.

Issue 150 opgelost

---

src/main/java/com/proj1/App.java
src/main/java/com/proj1/SaveManager.java
src/main/java/com/proj1/Student.java

Revert "Execute order 66"

---

database/oldDatabase.Wdf

Revert "ORDER 66"
